# Form implementation generated from reading ui file 'D:\WorkSpace\PycharmProjects\MyApplications\Study_PyQt6\StudyEng\engineering\frontend\gui\resources\ui\data_view.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(850, 726)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.today_word_label = QtWidgets.QLabel(parent=Form)
        self.today_word_label.setMaximumSize(QtCore.QSize(100, 100))
        self.today_word_label.setObjectName("today_word_label")
        self.verticalLayout.addWidget(self.today_word_label)
        self.today_word_num_label = QtWidgets.QLabel(parent=Form)
        self.today_word_num_label.setMaximumSize(QtCore.QSize(100, 100))
        self.today_word_num_label.setObjectName("today_word_num_label")
        self.verticalLayout.addWidget(self.today_word_num_label)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.total_word_label = QtWidgets.QLabel(parent=Form)
        self.total_word_label.setMaximumSize(QtCore.QSize(100, 100))
        self.total_word_label.setObjectName("total_word_label")
        self.verticalLayout_5.addWidget(self.total_word_label)
        self.total_word_num_label = QtWidgets.QLabel(parent=Form)
        self.total_word_num_label.setMaximumSize(QtCore.QSize(100, 100))
        self.total_word_num_label.setObjectName("total_word_num_label")
        self.verticalLayout_5.addWidget(self.total_word_num_label)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.toady_duration_label = QtWidgets.QLabel(parent=Form)
        self.toady_duration_label.setMaximumSize(QtCore.QSize(100, 100))
        self.toady_duration_label.setObjectName("toady_duration_label")
        self.verticalLayout_6.addWidget(self.toady_duration_label)
        self.today_duration_num_label = QtWidgets.QLabel(parent=Form)
        self.today_duration_num_label.setMaximumSize(QtCore.QSize(100, 100))
        self.today_duration_num_label.setObjectName("today_duration_num_label")
        self.verticalLayout_6.addWidget(self.today_duration_num_label)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.total_duration_label = QtWidgets.QLabel(parent=Form)
        self.total_duration_label.setMaximumSize(QtCore.QSize(100, 100))
        self.total_duration_label.setObjectName("total_duration_label")
        self.verticalLayout_7.addWidget(self.total_duration_label)
        self.total_duration_num_label = QtWidgets.QLabel(parent=Form)
        self.total_duration_num_label.setMaximumSize(QtCore.QSize(100, 100))
        self.total_duration_num_label.setObjectName("total_duration_num_label")
        self.verticalLayout_7.addWidget(self.total_duration_num_label)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.refresh_button = PushButton(parent=Form)
        self.refresh_button.setMinimumSize(QtCore.QSize(75, 0))
        self.refresh_button.setMaximumSize(QtCore.QSize(100, 40))
        self.refresh_button.setObjectName("refresh_button")
        self.horizontalLayout.addWidget(self.refresh_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.webEngineView = QtWebEngineWidgets.QWebEngineView(parent=Form)
        self.webEngineView.setMinimumSize(QtCore.QSize(0, 0))
        self.webEngineView.setUrl(QtCore.QUrl("about:blank"))
        self.webEngineView.setObjectName("webEngineView")
        self.verticalLayout_2.addWidget(self.webEngineView)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.today_word_label.setText(_translate("Form", "今日学习&复习"))
        self.today_word_num_label.setText(_translate("Form", "0"))
        self.total_word_label.setText(_translate("Form", "累计学习"))
        self.total_word_num_label.setText(_translate("Form", "0"))
        self.toady_duration_label.setText(_translate("Form", "今日学习时长"))
        self.today_duration_num_label.setText(_translate("Form", "0"))
        self.total_duration_label.setText(_translate("Form", "累计学习时长"))
        self.total_duration_num_label.setText(_translate("Form", "0"))
        self.refresh_button.setText(_translate("Form", "刷新"))
from PyQt6 import QtWebEngineWidgets
from qfluentwidgets import PushButton
from .. import resource_rc