# Form implementation generated from reading ui file 'D:\WorkSpace\PycharmProjects\MyApplications\Study_PyQt6\StudyEng\engineering\frontend\gui\resources\ui\main_page.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(850, 660)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 2)
        self.main_word_label = QtWidgets.QLabel(parent=Form)
        self.main_word_label.setMinimumSize(QtCore.QSize(400, 100))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.main_word_label.setFont(font)
        self.main_word_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.main_word_label.setObjectName("main_word_label")
        self.gridLayout.addWidget(self.main_word_label, 1, 1, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 0, 1, 1)
        self.learn_button = PushButton(parent=Form)
        self.learn_button.setMinimumSize(QtCore.QSize(250, 125))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.learn_button.setFont(font)
        self.learn_button.setObjectName("learn_button")
        self.gridLayout.addWidget(self.learn_button, 3, 1, 1, 1)
        self.review_button = PushButton(parent=Form)
        self.review_button.setMinimumSize(QtCore.QSize(250, 125))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.review_button.setFont(font)
        self.review_button.setObjectName("review_button")
        self.gridLayout.addWidget(self.review_button, 3, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem3, 3, 3, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.main_word_label.setText(_translate("Form", "TextLabel"))
        self.learn_button.setText(_translate("Form", "Learn\n"
"0"))
        self.review_button.setText(_translate("Form", "Review\n"
"0"))
from qfluentwidgets import PushButton
from .. import resource_rc